### PR TITLE
include mods from Roberval for the LA monitoring

### PR DESCRIPTION
**Pull request by mmusich**
This PR is meant to expose to the developing branch the changes from @robervalwalsh needed to include the variables for the LA monitoring in the calibration Trees.
Details are included in this [presentation](https://indico.cern.ch/event/688863/contributions/2973553/attachments/1638979/2616127/20180424_SiStripCalib_LorentzAngle.pdf).
Measuring the impact on the usual test file from 2017C I get an increase of the output file size **of about +23%**. 
The detailed break down is here:

gaincalibrationtreestdbunch_tree

@robervalwalsh can you please cross-check that all the variables are really needed? 
Thanks,

Marco

### CODE REVIEW

**Comment by robervalwalsh** [comment]
So far I removed the variable GainCalibrationdrifty, which is not really needed, and replaced GainCalibrationdriftx and GainCalibrationdriftz by their ratio, GainCalibrationdxoverdz.
The modifications are available in a branch of my github (https://github.com/robervalwalsh/cmssw/tree/from-CMSSW_9_2_15-calibtree). Shall I pull it here? If so, how? (I am not much expert on git)
More studies of combination and/or removal of variables are still ongoing, expected answer by 4 May.

**Comment by mmusich** [comment]
Hi @roberval, thanks for taking the time of reviewing your needs. I am partially offlline this week, so I am afraid we'll have to wait for the next one to finalize the PR and the measurement. I am waiting anyway for your final answer by May 4th.
Thanks!
cc: @echabert

**Comment by echabert** [comment]
Hi all,
sorry for being late to review. I had a look to the PR. For me it looks that only the "variance" is a variable which need to be compute cluster per cluster and thus should be kept as it is. However the other variables depends on B-field, Lorentz angle & geometry. If I don't miss something, they should be the same for all clusters of a given module during a given run. If this statement is true, thus I propose to create a new Tree in which we put the "global" variables (one entry per module). If so, I guess that we should create a different plugin.
@mmusich : what do you think ?
@robervalwalsh : if what I wrote is true, we can even keep all the variables we want per module if this hypothetical tree

**Comment by mmusich** [comment]
@echabert, indeed this is an excellent idea which should save lots of space. One would still need to save the detid cluster by cluster to do the linking among trees, but we should already have it. 
@robervalwalsh we can followup on this idea next week, unless of course you want to start writing the new plug-in yourself.
Cheers
M.

**Comment by robervalwalsh** [comment]
I think Eric is right. I can work on the plugin, but only in the week after next because I am on holidays next week.

**Comment by echabert** [comment]
Hi Roberval, it would be great. Thanks

**Comment by robervalwalsh** [comment]
This PR is superseded by PR #10

**Comment by mmusich** [comment]
closing as superseded by #10

**Pull request closed without merging**
