### PR TITLE
Include devel changes to production

### PR DESCRIPTION
**Pull request by mdelcourt**

### CODE REVIEW

**Review by mmusich — APPROVED** [review]
Thanks @mdelcourt, looks good to me. 
Feel free to merge it.

**Comment by echabert** [comment]
Looking to a recent run (calibTree_316186.root in eos), it appears that few variables are duplicated in evenInfo and gainCalibTree*: event, PU, lumi, ...
@mdelcourt: could you cross-check ?

**Comment by jlagram** [comment]
The gainCalibTree uses the same configuration file for the event information and inherit by default of all the event variables.

**Comment by echabert** [comment]
@clacaputo : could you fix this ? Thanks !

**Comment by mmusich** [comment]
@echabert and @jlagram, 
technically it can be disabled from configuration file: https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/python/ntuple_cff.py#L74,
but it is taking 4B/event..
Does not look like it's a bottleneck. 
Also it allows to cross-check the tree entries in the two ntuples.

**Pull request merged**
