### PR TITLE
add SiStripDetVOff information and check on the availability of the tag + force submit after 24h

### PR DESCRIPTION
**Pull request by mmusich**
As discussed in private e-mail thread I add here the changes to:
   * override the Express Global Tag to consume the SiStripDetVOff (DCS)  from the 13h delay tag `SiStripDetVOff_13hourDelay_v1_Validation`
   * check if the run number under consideration is fully covered by IOVs for the DCS (if not, skip the production)
   * check if the run is more than 24h old, and if the case force submit the calibTree production, irrespective of the fact that the express is not done. I chose 24h, but the time limit is debatable...

### CODE REVIEW

**Comment by jlagram** [comment]
Hi, the function isRunCoveredForTag never returns False ! I guess the line 'return False' is missing in the default case.

**Comment by mmusich** [comment]
Hi @jlagram, if it doens't explicitly return True, it returns False. I checked with a standalone script.

**Comment by jlagram** [comment]
ok!

**Comment by mmusich** [comment]
@echabert @pieterdavid @mdelcourt 
was this development integrated in the production area? Shall it be merged?

**Comment by pieterdavid** [comment]
We briefly discussed this last week. I also saw https://github.com/cms-sw/cmssw/pull/24474, which looks related. Do I understand correctly that this PR makes sure only runs that have the right condition are processed, and that the other is still needed to get the fraction every module was off? Should this also be added to the config for calibtree production, or is it run separately?

**Comment by mmusich** [comment]
>  I also saw cms-sw#24474, which looks related.

The CMSSW PR is loosely related. It adds a utility to print the fraction of time in which a given module was in the DetVOff list. 
This PR indeed makes sure that the 1h DCS O2O masking is applied at the tree creation time (that's the only correct way to take into account event-by-event unpowered modules in the hit efficiency) and that only runs which are covered by the 1h latency DCS O2O tag are submitted for the creation of the trees. 
The `SiStripDetVOffPrinter.cc` can be run on demand by the shifter to see which was the fraction of time with a given module unpowered (eventually the report can be made available to the offline SL).

**Comment by pieterdavid** [comment]
Since this is merged in the current production branch https://github.com/CMSTrackerDPG/cmssw/commits/CTproduction_updated I guess it would be best to also merge it into `CMSTrackerDPG:sitripCalibTreeDevel2018` (ideal the workflow should be PR -> devel; devel -> production, I suppose). There is a merge conflict, though. From the looks of it, only `calendar` still needs to be added to the imports (all others are not needed or already there). @mmusich can you confirm? It's easy to fix this in the merge commit

**Comment by mmusich** [comment]
Hi @pieterdavid I am slightly confused by the mechanism by which the conflict originated.
I see the development branch was updated by Martin with this commit: 
https://github.com/CMSTrackerDPG/cmssw/commit/dba99cfc1144d3a0d49fa83cfe47b4ac2c4d610d, for which I don't see a PR. 
I think it's fine to have brought the development branch up-to-date with CMSSW, but I think it won't merge anymore with the 10.1.X branch (as it is recommended in the recipe): https://github.com/orgs/CMSTrackerDPG/teams/sistripcalibtreedevel/discussions/1/comments/1.
Anyway I resolved by putting exactly what there is currently in the "production branch": https://github.com/CMSTrackerDPG/cmssw/blob/CTproduction_updated/CalibTracker/SiStripCommon/test/MakeCalibrationTrees/submitCalibTree/launchJobs.py 
to confuse less. 
Eventually we'll need to clean this up and put it in the *official* release (as there won't be production over LS2 and we need to store the developments for when we resume data-taking in run3).

**Comment by mmusich** [comment]
By the way, it seems it didn't work...
In the efficiency plots that were run yesterday (e.g. run 323472) I still see that there are these modules in TID+ Disk 2 found as inefficient:
```
TID+ Disk 2 :
		 402674309 	 1 	 1 1 1 	 1 1 1 1 1 1 
		 402674349 	 1 	 1 1 1 	 1 1 1 1 1 1 
		 402674353 	 1 	 1 1 1 	 1 1 1 1 1 1 
```

image

image

while they are masked in DCS tag [link to CondDB browser](https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/image_plot/Prod/CMSSW_10_3_0_pre4/eyJ0YWciOiJTaVN0cmlwRGV0Vk9mZl8xM2hvdXJEZWxheV92MV9WYWxpZGF0aW9uIiwicGxvdCI6InBsb3RfU2lTdHJpcERldFZPZmZfSXNNb2R1bGVWT2ZmX1RyYWNrZXJNYXAiLCJwbHVnaW4iOiJwbHVnaW5TaVN0cmlwRGV0Vk9mZl9QYXlsb2FkSW5zcGVjdG9yIiwidHlwZSI6IkltYWdlIiwiaW92cyI6eyJzdGFydF9pb3YiOiI2NjA0Nzg3MzE2Mzc4NzcxMDcyIiwiZW5kX2lvdiI6IjY2MDQ3ODczMTYzNzg3NzEwNzIifX0%3D)

image.

Confirmed also with J.L. tools:

```bash
cd CMSSW_10_3_X_2018-09-27-2300/src/
cmsenv
git cms-addpkg CalibTracker/SiStripDCS
scramv1 b -j 8
cd CalibTracker/SiStripDCS/python/
# adjust the dates to: 2018.09.24 16:49:54 | 2018.09.24 17:33:56
cmsRun dcs_print_summary_cfg.py
more PerModuleSummary.txt | grep '402674309\|402674349\|402674353'
```
which gives:

```
detId 402674309 #IOVs: 1  HVOff: 00:44:02 100%   LVOff: 00:00:00 0%
detId 402674349 #IOVs: 1  HVOff: 00:44:02 100%   LVOff: 00:00:00 0%
detId 402674353 #IOVs: 1  HVOff: 00:44:02 100%   LVOff: 00:00:00 0%
```

**Comment by pieterdavid** [comment]
Thanks @mmusich , I agree that this makes it a bit more difficult to follow (and we may need to clean up the git history at some point), but the default branch would still straightforwardly merge with master (see https://github.com/cms-sw/cmssw/compare/master...CMSTrackerDPG:sitripCalibTreeDevel2018), so I don't think it's a problem at this point (I see that @mdelcourt is using CMSSW_10_2_0 for the production, that probably motivated the update).
The changes are not in effect yet, in the end they were only merged this morning (the cron job should be running now).

**Comment by mmusich** [comment]
> The changes are not in effect yet, in the end they were only merged this morning (the cron job should be running now).

thanks a lot for the clarification!

**Pull request merged**
